----- Câu 36 -----
SELECT MASP , SUM(SL) AS SL
FROM HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE MONTH (NGHD) = 10 AND YEAR (NGHD) = 2006
GROUP BY MASP

----- Câu 37 -----
SELECT MONTH(NGHD) AS THANG , SUM(TRIGIA) AS TONGDOANHTHU
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)

----- Câu 38 -----
SELECT SOHD 
FROM CTHD
GROUP BY SOHD
HAVING COUNT(DISTINCT MASP) > 3

----- Câu 39 -----
SELECT SOHD 
FROM CTHD JOIN SANPHAM ON CTHD.MASP = SANPHAM.MASP
WHERE NUOCSX ='Viet Nam'
GROUP BY SOHD
HAVING COUNT(DISTINCT CTHD.MASP) = 3

----- Câu 40 -----
SELECT TOP 1 KHACHHANG.MAKH
FROM HOADON JOIN KHACHHANG ON HOADON.MAKH = KHACHHANG.MAKH
GROUP BY KHACHHANG.MAKH , HOTEN
ORDER BY COUNT(*) DESC

----- Câu 41 -----
SELECT TOP 1 MONTH(NGHD) AS THANG 
FROM HOADON
WHERE YEAR(NGHD) = 2006
GROUP BY MONTH(NGHD)
ORDER BY SUM(TRIGIA) DESC

----- Câu 42 -----
SELECT MASP 
FROM HOADON JOIN CTHD ON HOADON.SOHD = CTHD.SOHD
WHERE YEAR (NGHD) = 2006
GROUP BY MASP
ORDER BY SUM(SL) ASC

----- Câu 43 -----
SELECT NUOCSX , MASP , TENSP 
FROM SANPHAM
GROUP BY NUOCSX , MASP ,TENSP 
ORDER BY MAX(GIA) DESC

----- Câu 44 -----
SELECT NUOCSX
FROM SANPHAM
GROUP BY NUOCSX
HAVING COUNT(DISTINCT GIA) > 2

----- Câu 45 -----
SELECT TOP 1 MAKH ,HOTEN 
FROM (
		SELECT TOP 10 KHACHHANG.MAKH , KHACHHANG.HOTEN , COUNT(HOADON.MAKH) AS SL
		FROM  KHACHHANG JOIN HOADON ON KHACHHANG.MAKH = HOADON.MAKH
		GROUP BY KHACHHANG.MAKH , KHACHHANG.DOANHSO , KHACHHANG.HOTEN
		ORDER BY KHACHHANG.DOANHSO DESC
		) KH
ORDER BY SL DESC